import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {dollars,financeApi,financeError,type RecordData} from '../services/finance'
import MoneyInput from './MoneyInput'
import EquipmentStatementImport from './EquipmentStatementImport'
export type EquipmentPayment={id:string;date:string;principal:string;interest:string;evidence_id:string;allocation_note:string;facility:string;transaction?:{external_id:string;description:string;amount:string;account_id:string}}
export type PaymentSummary={principal_paid:string;interest_paid:string;payments_total:string;payment_count:number;remaining_from_records:string;payments:EquipmentPayment[];due:{due:string;amount:string;facility:string;evidence_id:string}|null}
type Asset=PaymentSummary&{id:number;name:string;vin:string;borrowed:string;facility:string;monthly_payment:string}
type Data={assets:Asset[];transactions:{id:string;date:string;amount:string;description:string;account_name:string;external_id:string}[]}
const input='block w-full rounded-md border border-slate-300 bg-white px-3 py-2 min-h-11'
const today=()=>new Date().toLocaleDateString('en-CA')
function Chevron({open}:{open:boolean}){return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true" className={open?'rotate-90':''}><path d="m9 18 6-6-6-6"/></svg>}
export default function EquipmentPayments(){
 const target=new URLSearchParams(window.location.search).get('equipment')
 const [open,setOpen]=useState(!!target),[data,setData]=useState<Data|null>(null),[assetId,setAssetId]=useState(target||''),[version,setVersion]=useState(0)
 const [mode,setMode]=useState<'payment'|'due'|null>(null),[importOpen,setImportOpen]=useState(false),[history,setHistory]=useState(false)
 const [txid,setTxid]=useState(''),[search,setSearch]=useState(''),[principal,setPrincipal]=useState(''),[interest,setInterest]=useState(''),[note,setNote]=useState(''),[facility,setFacility]=useState(''),[due,setDue]=useState(''),[amount,setAmount]=useState('')
 const [file,setFile]=useState<File|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [voidId,setVoidId]=useState(''),[reason,setReason]=useState('')
 useEffect(()=>{if(!open)return;let active=true;void financeApi.equipmentPayments(today()).then(r=>{if(active){setData(r);setAssetId(v=>v||String(r.assets[0]?.id||''))}}).catch(e=>{if(active)setMessage(financeError(e))});return()=>{active=false}},[open,version])
 const asset=data?.assets.find(a=>String(a.id)===assetId),tx=data?.transactions.find(t=>t.id===txid)
 const refresh=()=>setVersion(v=>v+1)
 const start=(next:'payment'|'due')=>{setMode(mode===next?null:next);setMessage('');setFile(null);setConfirmed(false);setFacility(asset?.facility||'');setDue(asset?.due?.due||'');setAmount(asset?.due?.amount||asset?.monthly_payment||'');setTxid('');setPrincipal('');setInterest('');setNote('')}
 const cents=(s:string)=>Math.round(Number(s.replace(/[$,]/g,''))*100)
 async function save(e:React.FormEvent){e.preventDefault();if(!asset||!file||!mode)return;setBusy(true);setMessage('');try{
  if(mode==='payment'&&(!tx||!confirmed||cents(principal)+cents(interest)!==-cents(tx.amount)))throw new Error('Principal plus interest must equal the selected bank payment.')
  const evidence=await financeApi.upload(file,`equipment:${asset.id}:${file.name}`,'')
  const payload:RecordData=mode==='due'?{kind:'equipment_payment_due',asset_id:asset.id,facility,due,amount:(cents(amount)/100).toFixed(2),evidence_id:evidence.id}:{kind:'equipment_payment',asset_id:asset.id,facility,transaction_id:txid,principal:(cents(principal)/100).toFixed(2),interest:(cents(interest)/100).toFixed(2),evidence_id:evidence.id,allocation_note:note,split_confirmed:true}
  await financeApi.command(mode==='due'?today():tx!.date,payload,crypto.randomUUID());setMode(null);refresh();setMessage(mode==='due'?'Due date saved. Make the payment at your bank.':'Payment recorded against this trailer. Its bank transaction cannot be used again.')
 }catch(error){setMessage(financeError(error))}finally{setBusy(false)}}
 async function remove(){setBusy(true);try{await financeApi.command(today(),{kind:'equipment_payment_void',payment_id:voidId,reason},crypto.randomUUID());setVoidId('');setReason('');refresh();setMessage('Payment record removed. Its original record and correction remain in the audit history.')}catch(e){setMessage(financeError(e))}finally{setBusy(false)}}
 return <section id="equipment-payments" className="rounded-xl border border-slate-200 bg-white p-4 sm:p-5">
 <button type="button" className="w-full flex justify-between items-center min-h-11 text-left font-semibold text-slate-900" aria-expanded={open} onClick={()=>setOpen(!open)}>Trailer payments<Chevron open={open}/></button>
 {open&&<div className="space-y-4 mt-3"><p className="text-sm text-slate-600">Plan the payment here, pay at your bank, then match the posted debit. A dedicated payment identifies the trailer’s share in ELIS; the HELOC lender still holds one account balance.</p>
 {!data?<p role="status">Loading payment records…</p>:!data.assets.length?<p>No financed trailer plans yet. <Link className="text-blue-700 underline" to="/trucks">Set up a trailer</Link></p>:<>
 <label className="block text-sm">Trailer<select className={input} value={assetId} onChange={e=>{setAssetId(e.target.value);setMode(null);setVoidId('');setMessage('')}}>{data.assets.map(a=><option key={a.id} value={a.id}>{a.name} · …{a.vin?.slice(-6)}</option>)}</select></label>
 {asset&&<><div className="grid sm:grid-cols-3 gap-3"><div className="rounded-lg bg-blue-50 p-3"><span className="text-sm text-slate-600">Monthly plan</span><strong className="block text-xl">{dollars(asset.monthly_payment)}</strong></div><div className="rounded-lg bg-slate-50 p-3"><span className="text-sm text-slate-600">Statement due date</span><strong className="block text-xl">{asset.due?.due||'Add from statement'}</strong>{asset.due&&<span className="text-sm">Planned payment {dollars(asset.due.amount)}</span>}</div><div className="rounded-lg bg-green-50 p-3"><span className="text-sm text-slate-600">Principal paid · recorded</span><strong className="block text-xl">{asset.payment_count?dollars(asset.principal_paid):'No payments matched'}</strong></div></div>
 <div className="flex flex-wrap gap-2"><button type="button" className="rounded-md border px-3 py-2 min-h-11" aria-expanded={mode==='due'} onClick={()=>start('due')}>Set next due date</button><button type="button" className="rounded-md bg-blue-700 text-white px-3 py-2 min-h-11" aria-expanded={mode==='payment'} onClick={()=>start('payment')}>Match a payment</button><Link className="text-blue-700 px-3 py-2 min-h-11" to={`/vehicles/${asset.id}`}>View trailer</Link></div>
 <button type="button" className="flex items-center gap-2 text-blue-700 min-h-11" aria-expanded={importOpen} onClick={()=>setImportOpen(!importOpen)}>Import bank statement<Chevron open={importOpen}/></button>
 {importOpen&&<EquipmentStatementImport onSaved={refresh}/>}
 {mode&&<form className="border rounded-lg p-4 space-y-3" onSubmit={e=>void save(e)}><h3 className="font-semibold">{mode==='due'?'Next trailer payment':'Record a dedicated trailer payment'}</h3>
 <label className="block text-sm">Lender / HELOC nickname<input required className={input} value={facility} onChange={e=>setFacility(e.target.value)}/></label>
 {mode==='due'?<div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Due date on statement<input required type="date" className={input} value={due} onChange={e=>setDue(e.target.value)}/></label><label className="text-sm">Amount you plan to pay<MoneyInput required className={input} value={amount} onChange={setAmount}/></label></div>:<>
 <label className="block text-sm">Find the posted bank payment<input type="search" placeholder="Amount, description or date" className={input} value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <div className="max-h-52 overflow-y-auto border rounded-lg">{data.transactions.filter(t=>[t.date,t.amount,t.description,t.account_name].join(' ').toLowerCase().includes(search.toLowerCase())).map(t=><label key={t.id} className="flex gap-3 p-3 border-b text-sm"><input required type="radio" name="equipment-bank-payment" checked={txid===t.id} onChange={()=>{setTxid(t.id);setConfirmed(false)}}/><span>{t.date} · {t.account_name}<span className="block">{t.description} · <strong>{dollars(-Number(t.amount))}</strong></span></span></label>)}{!data.transactions.length&&<p className="p-3 text-sm">No unmatched bank debits. Import the paying account’s statement above.</p>}</div>
 
 <div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Principal paid<MoneyInput required className={input} value={principal} onChange={setPrincipal}/></label><label className="text-sm">Interest paid<MoneyInput required className={input} value={interest} onChange={setInterest}/></label></div>
 {tx&&<p className="text-sm">Bank payment: {dollars(-Number(tx.amount))} · Split entered: {dollars((cents(principal)+cents(interest))/100)}</p>}
 <label className="block text-sm">How you assigned the interest to this trailer<textarea required className={input} value={note} onChange={e=>setNote(e.target.value)} placeholder="Statement period and the trailer share of HELOC interest"/></label>
 <label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the statement. This entire payment belongs to this trailer, and the interest/principal split is correct.</label>
 </>}
 <label className="block text-sm">HELOC / lender statement supporting these details<input type="file" required accept=".pdf,.png,.jpg,.jpeg,.csv" className="block mt-2" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>
 <p className="text-xs text-slate-500">Payment matching updates the trailer and Finance management view. It does not send money or post an acquisition or loan journal to Accounting.</p>
 <button disabled={busy||(mode==='payment'&&(!confirmed||!tx))} className="rounded-md bg-blue-700 text-white px-4 py-2 min-h-11 disabled:opacity-50">{busy?'Saving…':mode==='due'?'Save due date':'Record payment'}</button></form>}
 <button type="button" aria-expanded={history} className="flex w-full justify-between items-center min-h-11 text-sm" onClick={()=>setHistory(!history)}>Payment history · {asset.payment_count}<Chevron open={history}/></button>
 {history&&<div className="space-y-3">{asset.payments.map(p=><div key={p.id} className="border rounded-lg p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{p.date} · {dollars(Number(p.principal)+Number(p.interest))}</strong><span>Principal {dollars(p.principal)} · interest {dollars(p.interest)}</span></div><p>{p.facility} · Bank reference {p.transaction?.external_id}</p><p className="text-slate-600">{p.allocation_note}</p><div className="flex flex-wrap gap-4 mt-2"><button type="button" className="text-blue-700 min-h-11" onClick={()=>void financeApi.download(`/evidence/${p.evidence_id}/original`,'lender-statement')}>View statement</button><button type="button" className="text-slate-600 min-h-11" onClick={()=>setVoidId(voidId===p.id?'':p.id)}>Correct this record</button></div>{voidId===p.id&&<div className="space-y-2"><label>Reason for removing this match<input required className={input} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={busy||!reason.trim()} className="text-red-700 min-h-11" onClick={()=>void remove()}>Remove match and keep audit trail</button></div>}</div>)}{!asset.payments.length&&<p className="text-sm text-slate-600">No bank payments matched yet. Settlement allocations are still estimates.</p>}</div>}
 </>}
 </>}{message&&<p role="status" className="text-sm text-slate-700">{message}</p>}</div>}</section>
}
