import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {trucksApi} from '../services/api'
import {dollars} from '../services/finance'
import type {PaymentSummary} from './EquipmentPayments'
type Progress={original_borrowed:string;initial_cash:string;cash_recovery_target:string;sale_equity:string;week_start:string;week_end:string;weekly_loan_target:string;weekly_cash_target:string;unavailable?:string;as_of:string;start:string;source_count:number;allocated_income:string;loan_allocation:string;modeled_interest:string;modeled_principal_reduction:string;projected_balance:string;cash_recovery:string;cash_recovery_remaining:string;remaining_after_allocations:string;balance_target:string;target_date:string|null;planned_sale:string;repair_costs:string;estimated_free_cash:string;recorded_payments:PaymentSummary;sources:{id:number;date:string;kind:string;income:string;loan_allocation:string;cash_recovery:string}[]}
function Chevron({open}:{open:boolean}){return <svg width="16" height="16" viewBox="0 0 24 24" stroke="currentColor" fill="none" strokeWidth="2" aria-hidden="true" className={open?'rotate-90':''}><path d="m9 18 6-6-6-6"/></svg>}
export default function TrailerInvestmentProgress({id,revision}:{id:number;revision:number}) {
 const [data,setData]=useState<Progress|null>(null),[open,setOpen]=useState(false),[history,setHistory]=useState(false),[error,setError]=useState(false),[limit,setLimit]=useState(10)
 useEffect(()=>{let active=true;setError(false);void trucksApi.investmentProgress(id,new Date().toLocaleDateString('en-CA')).then(r=>{if(active)setData(r.data)}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[id,revision])
 if(error)return <p role="status" className="text-sm text-amber-800 mt-3">Payment progress could not be loaded. Reload to try again.</p>
 if(!data)return null
 if(data.unavailable)return <p className="text-sm text-amber-800 mt-3">{data.unavailable}</p>
 const financed=Number(data.original_borrowed)>0,paid=data.recorded_payments
 const metric=(name:string,value:string)=><div key={name} className="flex justify-between gap-3 py-1"><dt className="text-slate-600">{name}</dt><dd className="font-semibold tabular-nums">{dollars(value)}</dd></div>
 const loanCash=Math.max(Number(data.loan_allocation),Number(paid.payments_total)).toFixed(2)
 return <div className="mt-4">
 <p className="text-xs text-slate-500 mb-3">Trailer only · {data.start} – {data.as_of}</p>
 <div className="grid sm:grid-cols-3 gap-3">
 <section className="rounded-xl bg-blue-50 p-4"><h4 className="text-sm text-blue-900">{financed?'Borrowed':'Cash invested'}</h4><strong className="block text-2xl font-semibold mt-2 tabular-nums">{dollars(financed?data.original_borrowed:data.initial_cash)}</strong>{financed&&<p className="text-xs text-slate-600 mt-2">For this trailer only</p>}</section>
 <section className="rounded-xl bg-purple-50 p-4"><h4 className="text-sm text-purple-900">{financed?'Principal paid off':'Cash recovery · estimate'}</h4><strong className="block text-2xl font-semibold mt-2 tabular-nums">{financed?(paid.payment_count?dollars(paid.principal_paid):'Not confirmed'):dollars(data.cash_recovery)}</strong><p className="text-xs text-slate-600 mt-2">{financed?(paid.payment_count?`${dollars(paid.remaining_from_records)} remaining from recorded payments`:'Match a bank payment to show progress'): `${dollars(data.cash_recovery_remaining)} still to recover from earnings`}</p></section>
 <section className="rounded-xl bg-green-50 p-4"><h4 className="text-sm text-green-900">Free cash · estimate</h4><strong className="block text-2xl font-semibold mt-2 tabular-nums text-green-800">{dollars(data.estimated_free_cash)}</strong><p className="text-xs text-slate-600 mt-2">After loan budget, cash recovery and recorded repairs</p></section>
 </div>
 {financed&&<div className="flex flex-wrap justify-between items-center gap-2 mt-3 text-sm"><span className="text-slate-500">{paid.payment_count?`${paid.payment_count} bank payment${paid.payment_count===1?'':'s'} matched · interest paid ${dollars(paid.interest_paid)}`:'No bank payments matched yet.'}</span><Link className="text-blue-700 min-h-11 inline-flex items-center" to={`/bank-monitor?equipment=${id}`}>Record / review payments →</Link></div>}
 <button type="button" className="flex w-full items-center justify-between gap-3 text-sm min-h-11 mt-2" aria-expanded={open} onClick={()=>setOpen(!open)}>How these numbers add up<Chevron open={open}/></button>
 {open&&<div className="border-t pt-3 space-y-3"><dl className="text-sm">{metric('Trailer earnings in saved settlements',data.allocated_income)}{financed&&metric('Kept for loan payments',`-${loanCash}`)}{metric('Kept to recover your cash',`-${data.cash_recovery}`)}{metric('Recorded repairs',`-${data.repair_costs}`)}{metric('Estimated free cash',data.estimated_free_cash)}</dl>
 <p className="text-xs text-slate-500">This is estimated spendable earnings, not accounting net profit or a bank balance. Loan payments use the larger of the budget and matched payments. Missing costs and taxes can reduce it. Trailer earnings are already included in the truck + trailer total in Finance.</p>
 {financed&&<div className="rounded-lg bg-slate-100 p-3"><h4 className="text-sm font-semibold">Your own cash</h4><dl className="text-sm">{metric('Cash paid toward purchase and setup',data.initial_cash)}{metric('Recovery counted from earnings',data.cash_recovery)}{metric('Still to recover from earnings',data.cash_recovery_remaining)}</dl><p className="text-xs text-slate-500 mt-1">Recovery sets money aside for you. It does not prove a transfer to your personal account.</p></div>}
 <div className="rounded-lg bg-slate-100 p-3"><p className="text-xs text-slate-600 mb-1">Plan for last week · {data.week_start} – {data.week_end}</p><dl className="text-sm">{financed&&metric('Toward loan payments',data.weekly_loan_target)}{metric('Toward recovering your cash',data.weekly_cash_target)}</dl></div>
 {financed&&<p className="text-xs text-slate-500">Borrowing less recorded principal is your tracked trailer share, not the lender’s full HELOC balance. Unrecorded payments, fees or further borrowing need reconciliation.</p>}
 <button type="button" className="flex w-full items-center justify-between text-sm min-h-11" aria-expanded={history} onClick={()=>setHistory(!history)}>Settlement history · {data.source_count} records<Chevron open={history}/></button>{history&&<><p className="text-xs text-slate-500">These are budget allocations, not bank payments. Each settlement uses its share of the monthly plan.</p><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr><th className="py-2">Date</th><th>Income</th><th>Loan budget</th><th>Cash recovery</th></tr></thead><tbody>{data.sources.slice(0,limit).map(s=><tr key={s.id} className="border-t"><td className="py-2">{s.date}</td><td>{dollars(s.income)}</td><td>{dollars(s.loan_allocation)}</td><td>{dollars(s.cash_recovery)}</td></tr>)}</tbody></table></div>{limit<data.sources.length&&<button type="button" className="min-h-11 text-blue-700" onClick={()=>setLimit(limit+10)}>Show more</button>}</>}
 </div>}
 </div>
}
