export interface Field { name: string; label: string; type?: 'date' | 'money' | 'quantity' | 'number' | 'check' | 'select' | 'table'; options?: string[]; source?: string; optional?: boolean; initial?: string | boolean; columns?: Field[]; help?: string }
export interface Action { kind: string; label: string; help: string; fields: Field[] }
const evidence: Field = {name: 'evidence_id', label: 'Supporting document', type: 'select', source: 'evidence'}
const asset: Field = {name: 'asset_id', label: 'Asset', type: 'select', source: 'assets', optional: true}
const pair: Field = {name: 'pair_id', label: 'Truck earning pair', type: 'select', source: 'trucks'}
const amount: Field = {name: 'amount', label: 'Amount', type: 'money'}
const description: Field = {name: 'description', label: 'Description'}
const source: Field = {name: 'source_ref', label: 'Invoice / source reference', help: 'A unique reference prevents duplicate obligations.'}
const options = (name: string, label: string, values: string[]): Field => ({name, label, type: 'select', options: values})
const date = (name: string, label: string): Field => ({name, label, type: 'date'})
const category = options('category', 'Cost category', ['repairs', 'fuel', 'insurance', 'tolls', 'driver_pay', 'support', 'overhead', 'interest', 'equipment'])
const reserve: Field = {name: 'reserve_id', label: 'Cover with funded repair reserve', type: 'select', source: 'reserves', optional: true}
const claimFields = [{name: 'legacy_repair_id', label: 'Existing repair to link', type: 'select' as const, source: 'legacy_repairs', optional: true, help: 'Choose the existing repair when applicable. Its amount and payment status still need confirmation.'}, source, description, amount, category, asset, {...pair, optional: true}, reserve, evidence]
export const actions: Record<string, Action[]> = {
  money: [
    {kind: 'account', label: 'Add bank, card or cash account', help: 'Include every business account. Do not enter account numbers or credentials.', fields: [{name: 'name', label: 'Account nickname'}, options('account_type', 'Account type', ['bank', 'card', 'cash'])]},
    {kind: 'csv_mapping', label: 'Save CSV column mapping', help: 'Use stable transaction IDs from your bank or receipt references in your cashbook. Outflows and card charges must be negative; inflows and card repayments positive.', fields: [{name: 'name', label: 'Mapping name'}, ...['date', 'amount', 'description', 'id'].map(n => ({name: `${n}_column`, label: `${n === 'id' ? 'Transaction ID' : n} column heading`})), options('date_format', 'Date format', ['%Y-%m-%d', '%m/%d/%Y']), {name: 'invert_sign', label: 'Reverse amount signs', type: 'check'}, {name: 'approved_for_matching', label: 'Approve unique exact-reference matches after reconciliation', type: 'check'}]},
    {kind: 'statement', label: 'Reconcile a statement or cashbook', help: 'Upload the original CSV below first. Opening balance plus every imported transaction must equal closing balance. Card balances owed are negative. Cashbooks require a separate documented closing cash count.', fields: [{name: 'account_id', label: 'Account', type: 'select', source: 'account'}, {name: 'mapping_id', label: 'Saved CSV mapping', type: 'select', source: 'csv_mapping'}, evidence, {name: 'cash_count_evidence_id', label: 'Closing cash-count document (cash accounts only)', type: 'select', source: 'evidence', optional: true}, date('start', 'Statement start'), date('end', 'Statement end'), {name: 'opening', label: 'Opening balance', type: 'money'}, {name: 'closing', label: 'Closing balance', type: 'money'}, {name: 'supersedes_id', label: 'Replace an earlier statement', type: 'select', source: 'statement', optional: true}]},
    {kind: 'bill', label: 'Record a bill', help: 'Recognize the cost when incurred. Payment is recorded separately. A shared company bill has no asset.', fields: claimFields},
    {kind: 'owner_advance', label: 'Record owner-funded business cost', help: 'Creates one reimbursement claim and recognizes the supported cost or equipment acquisition. Personal spending belongs outside this record.', fields: claimFields},
    {kind: 'payment', label: 'Match a bill payment', help: 'A partial invoice payment is supported. Allocate this payment amount from the selected transaction. Multiple bills can share one transaction. Choose business for checking/Zelle, cash for business cash on hand, or owner for personally paid costs. Business cash must match a counted cashbook entry. A personal payment replaces the vendor obligation with an owner claim.', fields: [{name: 'claim_id', label: 'Unpaid obligation', type: 'select', source: 'claims'}, amount, options('payer', 'Paid by', ['business', 'owner', 'card', 'cash']), {name: 'transaction_id', label: 'Bank, card or cashbook transaction', type: 'select', source: 'transactions', optional: true}, {...evidence, optional: true}, {name: 'principal', label: 'Principal portion, if applicable', type: 'money', initial: '0.00'}, {name: 'interest', label: 'Interest portion, if applicable', type: 'money', initial: '0.00'}]},
    {kind: 'bank_match', label: 'Match a deposit or transfer', help: 'Settlement deposits clear receivables. Card repayments clear debt. Neither creates revenue or expense a second time.', fields: [{name: 'transaction_id', label: 'Bank or cashbook transaction', type: 'select', source: 'transactions'}, options('match_type', 'Match type', ['settlement', 'asset_sale', 'owner_contribution', 'owner_distribution', 'card_repayment', 'transfer']), {name: 'target_id', label: 'Settlement or equipment sale', type: 'select', source: 'receivables', optional: true}, {name: 'counterpart_transaction_id', label: 'Other side of transfer / card repayment', type: 'select', source: 'transactions', optional: true}, ...['operating', 'investing', 'financing'].map(n => ({name: `${n}_amount`, label: `Card repayment: ${n} portion`, type: 'money' as const, initial: '0.00', help: 'For card repayments, split the full payment using the underlying charges. Leave zero for other matches.'}))]},
    {kind: 'reserve', label: 'Fund or release a reserve', help: 'Earmarks cash already in the business. Positive amounts fund; negative amounts release. Repair funding takes priority over new capital funding.', fields: [pair, asset, options('purpose', 'Reserve purpose', ['repair', 'capital']), amount, {name: 'opening', label: 'Confirmed opening allocation', type: 'check'}, {name: 'note', label: 'Funding or release explanation'}, evidence]},
    {kind: 'financing', label: 'Record HELOC activity', help: 'Trace each business use. Link the existing owner claim; principal repayment does not create another claim or operating expense.', fields: [{name: 'facility', label: 'Facility nickname'}, options('action', 'Activity', ['draw', 'rate', 'interest', 'principal_payment', 'commitment']), amount, {name: 'business_amount', label: 'Supported business portion', type: 'money', initial: '0.00'}, {name: 'annual_rate', label: 'Annual interest rate (%)', type: 'quantity', initial: '6.5'}, asset, {name: 'owner_claim_id', label: 'Underlying business obligation', type: 'select', source: 'claims', optional: true}, {name: 'payment_id', label: 'Linked business payment', type: 'select', source: 'payment', optional: true}, {...date('due', 'Committed payment due'), optional: true}, {name: 'use_description', label: 'Use of proceeds / allocation explanation'}, evidence]},
  ],
  assets: [
    {kind: 'asset_plan', label: 'Set capital recovery plan', help: 'Acquisition cost less expected net resale is the funding target. The plan does not assert that historical profit was saved. Record the acquisition in the ledger separately.', fields: [{...asset, optional: false}, date('acquired', 'Acquired / placed in service'), {name: 'acquisition_cost', label: 'Supported acquisition cost', type: 'money'}, {name: 'expected_resale', label: 'Expected sale price', type: 'money'}, {name: 'selling_costs', label: 'Expected selling costs', type: 'money', initial: '0.00'}, date('planned_sale', 'Planned sale date'), {name: 'payoff_confirmed', label: 'Financing payoff verified from actual records', type: 'check'}, {name: 'payoff_evidence_id', label: 'Payoff evidence', type: 'select', source: 'evidence', optional: true}, evidence]},
    {kind: 'assignment', label: 'Assign a trailer to a truck', help: 'A new assignment ends any previous pairing the day before. Earlier history remains intact.', fields: [{name: 'truck_id', label: 'Truck', type: 'select', source: 'trucks'}, {name: 'trailer_id', label: 'Trailer', type: 'select', source: 'trailers'}, {...date('end', 'Assignment end'), optional: true}]},
    {kind: 'disposal', label: 'Record equipment sale', help: 'Recognize disposal once. Actual lender payoff is financing cash and is recorded separately from disposal gain.', fields: [{...asset, optional: false}, {name: 'gross_sale', label: 'Sale price', type: 'money'}, {name: 'selling_costs', label: 'Selling costs', type: 'money'}, {name: 'book_accumulated_depreciation', label: 'Verified accumulated book depreciation', type: 'money'}, {name: 'financing_payoff', label: 'Actual financing payoff', type: 'money', initial: '0.00'}, evidence]},
  ],
  settlements: [
    {kind: 'settlement', label: 'Review and post a settlement', help: 'Use original freight before the carrier share. Exclude internal trailer splits and reserve allocations. Every deduction and the reported remainder must reconcile exactly.', fields: [source, {...asset, optional: false}, {name: 'trailer_id', label: 'Attached trailer', type: 'select', source: 'trailers', optional: true}, date('period_start', 'Service period start'), date('period_end', 'Service period end'), {name: 'freight_gross', label: 'Original freight gross', type: 'money'}, {name: 'carrier_retention', label: 'Carrier retention', type: 'money'}, {name: 'reported_payout', label: 'Reported settlement remainder', type: 'money'}, {name: 'cash_adjustments', label: 'Non-operating cash adjustments', type: 'money', initial: '0.00'}, {name: 'miles', label: 'Settlement miles', type: 'quantity', optional: true}, options('mileage_basis', 'Mileage evidence', ['reported', 'independent', 'estimated', 'allocated']), {name: 'deductions', label: 'Operating deductions', type: 'table', columns: [options('category', 'Category', ['driver_pay', 'fuel', 'insurance', 'tolls', 'support', 'repairs', 'overhead', 'interest', 'other_expense']), amount]}, {name: 'fuel', label: 'Fuel purchase rows', type: 'table', columns: [date('date', 'Date'), {name: 'gallons', label: 'Gallons', type: 'quantity', optional: true}, amount, options('product', 'Product', ['unknown', 'diesel', 'def']), {name: 'location', label: 'Location'}, {name: 'discount', label: 'Discount', type: 'money', optional: true}, {name: 'source_row', label: 'Original row'}]}, {name: 'loads', label: 'Load rows', type: 'table', columns: [{name: 'load_id', label: 'Load ID'}, date('pickup', 'Pickup'), date('delivery', 'Delivery'), {name: 'empty_miles', label: 'Empty miles', type: 'quantity'}, {name: 'loaded_miles', label: 'Loaded miles', type: 'quantity'}, {name: 'freight_gross', label: 'Freight gross', type: 'money'}, {name: 'source_row', label: 'Original row'}]}, evidence]},
  ],
  connections: [
    {kind: 'travel', label: 'Record verified travel interval', help: 'Use Motive or odometer readings. Gallons purchased are not gallons consumed. Only supported consumption and independent distance can produce measured MPG.', fields: [{...asset, optional: false}, date('start', 'Interval start'), date('end', 'Interval end'), {name: 'miles', label: 'Independent miles', type: 'quantity'}, options('basis', 'Distance source', ['motive', 'odometer', 'estimated']), {name: 'consumed_gallons', label: 'Supported consumed gallons', type: 'quantity', optional: true}, {name: 'consumption_supported', label: 'Consumption interval supported by evidence', type: 'check'}, options('classification', 'Movement classification', ['unresolved', 'loaded', 'deadhead', 'maintenance', 'repositioning']), {name: 'baseline_mpg', label: 'Measured truck baseline MPG', type: 'quantity', optional: true}, evidence]},
    {kind: 'completed_load', label: 'Record a completed load', help: 'Requires completed-load evidence. GPS movement alone is insufficient. Flag when unmatched after two settlement cycles.', fields: [{...asset, optional: false}, {name: 'load_id', label: 'Load ID'}, {name: 'settlement_cycle_days', label: 'Expected settlement cycle (days)', type: 'number', initial: '7'}, evidence]},
  ],
  accounting: [
    {kind: 'policy', label: 'Confirm accounting setup', help: 'Confirm each item only after reviewing supporting records. Incomplete setup keeps reports in draft. Tax basis and management reserves remain separate.', fields: [{name: 'timezone', label: 'Business timezone', initial: 'America/New_York'}, {name: 'repair_weekly_target', label: 'Weekly repair target per pair', type: 'money', initial: '300.00'}, ...[['approved', 'Accounting policy approved'], ['opening_confirmed', 'Opening balances confirmed'], ['account_coverage_confirmed', 'All business bank, card and cash accounts included'], ['history_confirmed', 'Historical source coverage confirmed'], ['carrier_presentation_confirmed', 'Carrier gross/net presentation confirmed'], ['owner_treatment_confirmed', 'Owner funding and mixed-use interest policy confirmed'], ['depreciation_confirmed', 'Book depreciation confirmed'], ['tax_basis_confirmed', 'Prior tax basis and elections confirmed']].map(([name, label]) => ({name, label, type: 'check' as const})), {...evidence, name: 'policy_evidence', optional: true}]},
    {kind: 'journal', label: 'Post a supported journal', help: 'Use for confirmed opening balances, depreciation and accountant adjustments. Debits and credits must balance. Ordinary bills and payments belong in Money.', fields: [description, evidence, options('cash_flow_classification', 'Cash-flow treatment', ['noncash', 'opening', 'operating', 'investing', 'financing']), {name: 'lines', label: 'Journal lines', type: 'table', columns: [{name: 'account', label: 'Account', type: 'select', source: 'ledger_accounts'}, {name: 'debit', label: 'Debit', type: 'money', initial: '0.00'}, {name: 'credit', label: 'Credit', type: 'money', initial: '0.00'}, asset]}]},
    {kind: 'reversal', label: 'Reverse a posting', help: 'Preserve the original and post an exact reversal with a reason. Closed periods require reopening or a current-period correction.', fields: [{name: 'posting_id', label: 'Posting ID'}, {name: 'reason', label: 'Reason for correction'}]},
    {kind: 'close_period', label: 'Close a period', help: 'Requires reconciled balances, matched transactions, source coverage and approved policy.', fields: [date('start', 'Period start'), date('end', 'Period end'), {name: 'reason', label: 'Closing note'}]},
    {kind: 'reopen_period', label: 'Reopen a period', help: 'The reason remains in the audit trail. Previous report snapshots remain unchanged.', fields: [date('start', 'Period start'), date('end', 'Period end'), {name: 'reason', label: 'Reason to reopen'}]},
  ],
}
actions.repairs = [actions.money[3], actions.money[5], actions.money[7]]

actions.money.push({kind: 'credit_note', label: 'Record a credit or refund', help: 'A credit reduces an unpaid obligation. A paid-cost refund must match its bank or card transaction. The original cost remains traceable.', fields: [{name: 'claim_id', label: 'Original obligation', type: 'select', source: 'claims'}, amount, description, evidence, {name: 'transaction_id', label: 'Incoming refund transaction (paid costs only)', type: 'select', source: 'transactions', optional: true}]})

actions.accounting.push({kind: 'activate_finance', label: 'Make reconciled finance the home page', help: 'Switch this business after its current report passes all reconciliation checks and the browser workflows have been accepted. Legacy reports remain available.', fields: [{name: 'browser_acceptance_confirmed', label: 'The browser workflows and current reconciled report have been reviewed and accepted', type: 'check'}]})
