import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Context, Report, dollars, financeApi, financeError } from '../../services/finance'
import { HistoryReport } from './historyTypes'
import HistoryTrend from './HistoryTrend'
import '../../pages/OwnerDashboard.css'
const names: Record<string,string> = {freight:'Freight revenue',carrier:'Carrier retention',fuel:'Fuel purchases',driver_pay:'Driver pay',insurance:'Insurance',tolls:'Tolls',support:'Support',fleet_manager_support:'Support',remainder:'Settlement remainder'}
const colors: Record<string,string> = {carrier:'#64748b',fuel:'#b45309',driver_pay:'#7c3aed',insurance:'#475569',tolls:'#a16207',support:'#9f1239',remainder:'#1d4ed8'}
const name = (k: string) => names[k] || k.replace(/_/g,' ')
export default function OwnerOverview({report:r,context}: {report:Report;context:Context}) {
  const [history,setHistory] = useState<HistoryReport|null>(null)
  const [error,setError] = useState('')
  const [retry,setRetry] = useState(0)
  useEffect(()=>{let active=true;setHistory(null);setError('');financeApi.history().then(h=>{if(active)setHistory(h)}).catch(e=>{if(active)setError(financeError(e))});return()=>{active=false}},[context.tenant_id,retry])
  const pairs = r.owner_insights.pairs.filter(p=>p.statement_count)
  const gross = Number(r.revenue_breakdown.freight_gross)
  const remainder = Number(r.revenue_breakdown.settlement_remainder)
  const breakdown = [...r.revenue_breakdown.rows.map(x=>({key:x.category,value:Number(x.amount)})),{key:'remainder',value:remainder}]
  const cash = r.owner_cash
  return <div className="owner-dashboard">
    <section className="owner-panel owner-cash"><div><h2>Business total · available to owner</h2><p className="owner-cash-number">{cash.available===null?'Cash needs reconciliation':dollars(cash.available)}</p><p className="finance-help">As of {cash.as_of} · {cash.status==='reconciled'?'Reconciled':'Provisional'}. Settlement earnings are shown separately below.</p></div><div><Link className="finance-secondary" to="/finance/money">Reconcile business cash</Link><p className="finance-help">Protect repair and capital funds, unpaid bills and scheduled financing before taking money home.</p></div>
    <details className="owner-details"><summary>Cash coverage and protected funds</summary><dl className="finance-waterfall">{[['Bank cash',cash.business_cash],['Funded reserves',cash.protected_reserves],['Uncovered bills',cash.uncovered_bills],['Owner reimbursements',cash.owner_reimbursement],['Card obligations',cash.card_obligations],['Committed financing',cash.committed_financing]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{dollars(v)}</dd></div>)}</dl>{cash.issues.map(x=><p className="finance-help" key={x}>{x}</p>)}</details></section>
    <section className="owner-panel"><div className="finance-section-heading"><h2>Where the freight revenue goes</h2><Link to="/settlements/reconciliation">Review original statements</Link></div>
    {r.owner_insights.unposted_in_period > 0 && <p className="finance-error">Partial period: {r.owner_insights.unposted_in_period} existing settlements are not yet posted in this view. These figures do not represent the complete period. <Link to="/settlements/reconciliation">Review missing statements</Link></p>}
    {gross>0?<><div className="owner-flow-totals"><span>Freight billed<strong>{dollars(gross)}</strong></span><span>Statement remainder<strong>{dollars(remainder)}</strong><small>{(remainder/gross*100).toFixed(1)}% retained before outside bills and cash protection</small></span></div>
    <div className="owner-stacked" role="img" aria-label="Share of original freight; exact figures follow">{breakdown.filter(x=>x.value>0).map(x=><span key={x.key} style={{flexGrow:x.value,background:colors[x.key]||'#475569'}} />)}</div>
    <div className="owner-breakdown">{breakdown.map(x=><div key={x.key}><span><i style={{background:colors[x.key]||'#475569'}} />{name(x.key)}</span><strong>{dollars(x.value)}</strong><small>{(x.value/gross*100).toFixed(1)}% of freight</small></div>)}</div><p className="finance-help">Carrier and driver amounts show their settlement share, not their personal take-home. Internal trailer allocations stay inside your business; reserves are not operating expenses.</p></>:<p className="finance-empty">No reviewed statements posted for this period. <Link to="/settlements/reconciliation">Explore the historical review</Link>.</p>}
    </section>
    <section className="owner-panel"><div className="finance-section-heading"><h2>Truck + trailer performance</h2><Link to="/finance/assets">Equipment and capital</Link></div>
      <div className="owner-pairs">{pairs.map(p=><article key={p.asset_id}><h3>{p.name}</h3><p className="finance-help">{p.trailer_ids.map(id=>context.assets.find(a=>a.id===id)?.name).join(' · ')||'Trailer assignment not established'}</p><div className="owner-pair-result"><strong>{dollars(p.remainder)}</strong><span>statement remainder · {p.remainder_percent}% of freight</span></div><div className="owner-stacked owner-pair-bar" role="img" aria-label={`Expense shares and remainder for ${p.name}; figures below`}>{[...Object.entries(p.categories),['remainder',p.remainder]].filter(([,v])=>Number(v)>0).map(([k,v])=><span key={k} style={{flexGrow:Number(v),background:colors[k]||'#475569'}} />)}</div>
        <div className="owner-metrics"><span>Statement remainder / calendar day<strong>{dollars(p.remainder_per_calendar_day)}</strong></span><span>Fuel cost / reported mile<strong>{p.fuel_per_mile?`$${p.fuel_per_mile}`:'Not established'}</strong></span><span>Remainder / reported mile<strong>{p.remainder_per_mile?`$${p.remainder_per_mile}`:'Not established'}</strong></span><span>Empty miles<strong>{p.empty_mile_percent?`${p.empty_mile_percent}%`:'Not established'}</strong></span></div>
        <details className="owner-details"><summary>Costs, pair split and sources</summary><dl className="finance-waterfall">{Object.entries(p.categories).map(([k,v])=><div key={k}><dt>{name(k)}</dt><dd>{dollars(v)} · {p.shares[k]}%</dd></div>)}<div><dt>Reported distance</dt><dd>{p.miles||'Not established'} mi</dd></div><div><dt>Recorded costs outside statements</dt><dd>{dollars(-Number(p.outside_statement_effect))}</dd></div></dl><p className="finance-help">Truck–trailer allocations do not change combined earnings. The original allocation split is available in each settlement review. Daily values use all {r.period.calendar_days} calendar days selected, including downtime.</p><Link to={`/settlements/reconciliation?asset=${p.asset_id}`}>Open source history</Link></details>
      </article>)}</div>
      {r.owner_insights.comparisons.map((c,i)=><div className="owner-explanation" key={i}><h3>What explains the difference?</h3><p>{c.compared_name} has a <strong>{dollars(c.difference)}</strong> difference in statement remainder compared with {c.base_name}.</p><div className="owner-delta" role="list">{c.effects.map(e=><div role="listitem" key={e.category}><span>{name(e.category)}</span><div className="owner-delta-track"><i style={{width:`${Math.abs(Number(e.amount))/Math.max(...c.effects.map(x=>Math.abs(Number(x.amount))))*100}%`,background:Number(e.amount)<0?'#b45309':'#1d4ed8'}} /></div><strong>{Number(e.amount)>0?'+':''}{dollars(e.amount)}</strong></div>)}</div>{c.fuel_rate_change_percent&&<p>Fuel spending per reported mile differs by <strong>{c.fuel_rate_change_percent}%</strong>.</p>}<p className="finance-help">{c.note}</p></div>)}
      <div className="finance-company-row"><span>Shared company result · recorded once</span><strong>{dollars(r.shared_company_result)}</strong></div><p className="finance-help">{r.owner_insights.note} Missing outside expenses must be reconciled before calling this final profit.</p>
    </section>
    <section className="owner-panel"><div className="finance-section-heading"><h2>Investigate next</h2><Link to="/settlements/reconciliation">Review all history</Link></div><ul className="owner-issues">{r.owner_insights.issues.map((x,i)=><li key={i}><strong>{x.title}</strong><p>{x.detail}</p><Link to={x.code==='service_date'?'/settlements/reconciliation':x.href}>Review evidence</Link></li>)}{history&&<li><strong>{history.coverage.source_records} historical settlements inventoried</strong><p>{history.coverage.arithmetic_matched} arithmetic-matched originals; {history.coverage.originals_need_review} need source review; {history.coverage.missing_sources} originals are unavailable. Possible losses remain investigation items until corroborated.</p><Link to="/settlements/reconciliation">Open reconciliation history</Link></li>}</ul>{!r.owner_insights.issues.length&&!history&&<p className="finance-help">Source history is loading. Accounting readiness remains available below.</p>}<details className="owner-details"><summary>Accounting and setup readiness</summary><ul className="owner-issues">{r.exceptions.map((x,i)=><li key={i}><Link to={x.href}>{x.message}</Link></li>)}</ul></details></section>
    <section className="owner-panel">{history?<HistoryTrend history={history}/>:error?<div role="alert">{error}<button className="finance-secondary" onClick={()=>setRetry(retry+1)}>Retry history</button></div>:<p role="status">Loading historical trends…</p>}</section>
  </div>
}
